In [1]:
from sklearn.svm import SVC

In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import datasets

In [9]:
df = datasets.load_iris(as_frame = True).frame
df.isnull().sum()
df.shape
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [10]:
x = df.drop("target",axis=1)
y = df["target"]
x.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [11]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3,random_state = 42,stratify = y)

In [12]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [16]:
# RBF KERNEL (this is by default)

svc = SVC()
svc.fit(x_train_scaled,y_train)
y_pred = svc.predict(x_test_scaled)

from sklearn.metrics import accuracy_score,classification_report

print("accuracy score : ",accuracy_score(y_test,y_pred))
print("classification report : \n",classification_report(y_test,y_pred))

accuracy score :  0.9333333333333333
classification report :
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       0.88      0.93      0.90        15
           2       0.93      0.87      0.90        15

    accuracy                           0.93        45
   macro avg       0.93      0.93      0.93        45
weighted avg       0.93      0.93      0.93        45

In [17]:
# Linear kernel

svc = SVC(kernel = "linear")
svc.fit(x_train_scaled,y_train)
y_pred = svc.predict(x_test_scaled)

print("accuracy_score is : ",accuracy_score(y_test,y_pred))

accuracy_score is :  0.9111111111111111

In [18]:
# polynomial kernel...

svc = SVC(kernel = "poly")
svc.fit(x_train_scaled,y_train)
y_pred = svc.predict(x_test_scaled)

print("accuracy_score is : ",accuracy_score(y_test,y_pred))

accuracy_score is :  0.8666666666666667

In [19]:
# sigmoid kernel ....

svc = SVC(kernel = "sigmoid")
svc.fit(x_train_scaled,y_train)
y_pred = svc.predict(x_test_scaled)

print("accuracy_score is : ",accuracy_score(y_test,y_pred))

accuracy_score is :  0.9111111111111111

In [20]:
# hyperparameter tuning....

C_vals = [0.5,1,2,3,4,5]

for c_val in C_vals :
    svc = SVC(C = c_val,kernel = "rbf")
    svc.fit(x_train_scaled,y_train)
    y_pred = svc.predict(x_test_scaled)
    print("C = ",c_val, "& accuracy : ",accuracy_score(y_test,y_pred))

C =  0.5 & accuracy :  0.9111111111111111
C =  1 & accuracy :  0.9333333333333333
C =  2 & accuracy :  0.9111111111111111
C =  3 & accuracy :  0.9111111111111111
C =  4 & accuracy :  0.9333333333333333
C =  5 & accuracy :  0.9333333333333333